platform: linux
image_resource:
  type: docker-image
  source: {repository: quay.io/desource/alpine, tag: build}
  
run:
  path: src/build.sh
  
inputs:
  - name: liblua-src
    path: src

outputs:
  - name: lua-build
